export type RbThemeName = 'light' | 'dark';
export declare const scaleColors: {
    readonly "red-500": "#fb2c36";
    readonly "red-600": "#e7000b";
    readonly "red-alpha-50p": "#fb2c3680";
    readonly "red-alpha-30p": "#fb2c364d";
    readonly "red-alpha-10p": "#fb2c361a";
    readonly "red-alpha-20p": "#fb2c3633";
    readonly "orange-500": "#ff6900";
    readonly "orange-600": "#f54a00";
    readonly "orange-alpha-50p": "#ff690080";
    readonly "orange-alpha-30p": "#ff69004d";
    readonly "orange-alpha-10p": "#ff69001a";
    readonly "orange-alpha-20p": "#ff690033";
    readonly "green-500": "#00c951";
    readonly "green-600": "#00a63e";
    readonly "green-alpha-50p": "#00c95180";
    readonly "green-alpha-30p": "#00c9514d";
    readonly "green-alpha-10p": "#00c9511a";
    readonly "green-alpha-20p": "#00c95133";
    readonly "blue-500": "#2b7fff";
    readonly "blue-600": "#155dfc";
    readonly "blue-alpha-50p": "#2b7fff80";
    readonly "blue-alpha-30p": "#2b7fff4d";
    readonly "blue-alpha-10p": "#2b7fff1a";
    readonly "blue-alpha-20p": "#2b7fff33";
    readonly "zinc-950-alpha-5": "#09090b0d";
    readonly "zinc-950-alpha-10": "#09090b1a";
    readonly "zinc-950-alpha-15": "#09090b26";
    readonly "zinc-950-alpha-20": "#09090b33";
    readonly "zinc-950-alpha-25": "#09090b40";
    readonly "zinc-950-alpha-30": "#09090b4d";
    readonly "zinc-950-alpha-40": "#09090b66";
    readonly "zinc-950-alpha-50": "#09090b80";
    readonly "zinc-950-alpha-60": "#09090b99";
    readonly "zinc-950-alpha-70": "#09090bb3";
    readonly "zinc-950-alpha-75": "#09090bbf";
    readonly "zinc-950-alpha-80": "#09090bcc";
    readonly "zinc-950-alpha-85": "#09090bd9";
    readonly "zinc-950-alpha-90": "#09090be6";
    readonly "zinc-950-alpha-95": "#09090bf2";
    readonly "zinc-50-alpha-5": "#fafafa0d";
    readonly "zinc-50-alpha-10": "#fafafa1a";
    readonly "zinc-50-alpha-15": "#fafafa26";
    readonly "zinc-50-alpha-20": "#fafafa33";
    readonly "zinc-50-alpha-25": "#fafafa40";
    readonly "zinc-50-alpha-30": "#fafafa4d";
    readonly "zinc-50-alpha-40": "#fafafa66";
    readonly "zinc-50-alpha-50": "#fafafa80";
    readonly "zinc-50-alpha-60": "#fafafa99";
    readonly "zinc-50-alpha-70": "#fafafab3";
    readonly "zinc-50-alpha-75": "#fafafabf";
    readonly "zinc-50-alpha-80": "#fafafacc";
    readonly "zinc-50-alpha-85": "#fafafad9";
    readonly "zinc-50-alpha-90": "#fafafae6";
    readonly "zinc-50-alpha-95": "#fafafaf2";
    readonly "zinc-50": "#fafafa";
    readonly "zinc-100": "#f4f4f5";
    readonly "zinc-200": "#e4e4e7";
    readonly "zinc-300": "#d4d4d8";
    readonly "zinc-400": "#9f9fa9";
    readonly "zinc-500": "#71717b";
    readonly "zinc-600": "#52525c";
    readonly "zinc-700": "#3f3f46";
    readonly "zinc-800": "#232326";
    readonly "zinc-900": "#18181b";
    readonly "zinc-950": "#09090b";
    readonly "base-black": "#000000";
    readonly "base-transparent": "#ffffff00";
    readonly "base-white": "#ffffff";
    readonly "yellow-400": "#fcc800";
    readonly "yellow-500": "#efb100";
    readonly "yellow-alpha-50p": "#fcc80080";
    readonly "yellow-alpha-30p": "#fcc8004d";
    readonly "yellow-alpha-10p": "#fcc8001a";
    readonly "yellow-alpha-20p": "#fcc80033";
    readonly "primary-alpha-10p": "#155dfc1a";
    readonly "primary-alpha-30p": "#155dfc4d";
    readonly "primary-stronger": "#003baf";
    readonly "primary-strong": "#154dd0";
    readonly "primary-alpha-50p": "#155dfc80";
    readonly "primary-normal": "#155dfc";
    readonly "custom-gray-100": "#18181a";
    readonly "custom-gray-200": "#1f1f22";
    readonly "custom-gray-300": "#2a2a2d";
    readonly "violet-500": "#8e51ff";
    readonly "violet-600": "#7f22fe";
    readonly "violet-alpha-50p": "#8e51ff80";
    readonly "violet-alpha-30p": "#8e51ff4d";
    readonly "violet-alpha-20p": "#8e51ff33";
    readonly "violet-alpha-10p": "#8e51ff1a";
    readonly "rainbow-normal": "#e6331b";
    readonly "rainbow-strong": "#cf2d18";
    readonly "rainbow-stronger": "#b82815";
    readonly "rainbow-alpha-50p": "#e6331b80";
    readonly "rainbow-alpha-30p": "#e6331b4d";
    readonly "rainbow-alpha-10p": "#e6331b1a";
    readonly "icon-primary": "#5c9cff";
    readonly "navy-normal": "#0b558c";
    readonly "navy-strong": "#094a7a";
    readonly "navy-stronger": "#073e67";
    readonly "navy-alpha-50p": "#0b558c80";
    readonly "navy-alpha-30p": "#082a6c4d";
    readonly "navy-alpha-10p": "#082a6c1a";
    readonly "navy-alpha-20p": "#0b558c33";
    readonly "navy-alpha-15p": "#0b558c26";
};
export declare const colors: {
    readonly light: {
        readonly "fg-default": "#09090b";
        readonly "fg-danger-subtle": "#fb2c3680";
        readonly "fg-danger": "#fb2c36";
        readonly "fg-warning-subtle": "#ff690080";
        readonly "fg-warning": "#ff6900";
        readonly "fg-success-subtle": "#00c95180";
        readonly "fg-success": "#00a63e";
        readonly "fg-information-subtle": "#2b7fff80";
        readonly "fg-information": "#2b7fff";
        readonly "fg-disabled": "#09090b40";
        readonly "fg-inverse": "#fafafa";
        readonly "fg-subtlest": "#09090b66";
        readonly "fg-subtle": "#09090bb3";
        readonly "fg-subtler": "#09090b99";
        readonly "fg-inverse-disabled": "#fafafa33";
        readonly "fg-brand": "#155dfc";
        readonly "fg-brand-subtle": "#155dfc80";
        readonly "fg-default-hovered": "#09090bcc";
        readonly "fg-brand-hovered": "#154dd0";
        readonly "fg-caution": "#fcc800";
        readonly "fg-caution-subtle": "#fcc80080";
        readonly "fg-static-white": "#ffffff";
        readonly "fg-static-white-subtle": "#71717b";
        readonly "fg-debug": "#8e51ff";
        readonly "fg-debug-subtle": "#8e51ff80";
        readonly "fg-rb": "#e6331b";
        readonly "fg-rb-subtle": "#e6331b80";
        readonly "fg-navy": "#0b558c";
        readonly "fg-navy-subtle": "#0b558c80";
        readonly "fg-navy-hovered": "#094a7a";
        readonly "border-default": "#09090b33";
        readonly "border-danger-stronger": "#fb2c36";
        readonly "border-warning-stronger": "#ff6900";
        readonly "border-success-stronger": "#00c951";
        readonly "border-information-stronger": "#2b7fff";
        readonly "border-disabled": "#09090b0d";
        readonly "border-inverse-stronger": "#fafafae6";
        readonly "border-stronger": "#09090be6";
        readonly "border-inverse": "#fafafa4d";
        readonly "border-danger": "#fb2c3680";
        readonly "border-warning": "#ff690080";
        readonly "border-information": "#2b7fff80";
        readonly "border-success": "#00c95180";
        readonly "border-subtle": "#09090b26";
        readonly "border-input-focused": "#09090be6";
        readonly "border-inverse-disabled": "#fafafa1a";
        readonly "border-brand-stronger": "#155dfc";
        readonly "border-brand": "#155dfc80";
        readonly "border-caution-stronger": "#fcc800";
        readonly "border-caution": "#fcc80080";
        readonly "border-debug-stronger": "#8e51ff";
        readonly "border-debug": "#8e51ff80";
        readonly "border-subtler": "#09090b1a";
        readonly "border-rb-stronger": "#e6331b";
        readonly "border-rb": "#e6331b80";
        readonly "border-navy-stronger": "#0b558c";
        readonly "border-navy": "#0b558c80";
        readonly "fill-danger-subtle": "#fb2c364d";
        readonly "fill-danger": "#fb2c36";
        readonly "fill-warning-subtle": "#ff69004d";
        readonly "fill-warning": "#ff6900";
        readonly "fill-success-subtle": "#00c9514d";
        readonly "fill-success": "#00c951";
        readonly "fill-information-subtle": "#2b7fff4d";
        readonly "fill-information": "#2b7fff";
        readonly "fill-disabled": "#09090b0d";
        readonly "fill-control-surface": "#fafafa";
        readonly "fill-inverse": "#f4f4f5";
        readonly "fill-inverse-hovered": "#d4d4d8";
        readonly "fill-subtle": "#09090b66";
        readonly "fill-subtle-hovered": "#09090b4d";
        readonly "fill-transparent": "#ffffff00";
        readonly "fill-transparent-hovered": "#09090b0d";
        readonly "fill-default": "#18181b";
        readonly "fill-default-hovered": "#3f3f46";
        readonly "fill-inverse-subtle": "#fafafa66";
        readonly "fill-inverse-subtle-hovered": "#fafafa4d";
        readonly "fill-inverse-disabled": "#fafafa1a";
        readonly "fill-brand": "#155dfc";
        readonly "fill-brand-subtle": "#155dfc80";
        readonly "fill-subtler": "#09090b33";
        readonly "fill-subtler-hovered": "#09090b26";
        readonly "fill-brand-hovered": "#154dd0";
        readonly "fill-control-surface-hovered": "#f4f4f5";
        readonly "fill-caution-subtle": "#fcc8004d";
        readonly "fill-caution": "#fcc800";
        readonly "fill-danger-subtler": "#fb2c3633";
        readonly "fill-warning-subtler": "#ff690033";
        readonly "fill-caution-subtler": "#fcc80033";
        readonly "fill-success-subtler": "#00c95133";
        readonly "fill-information-subtler": "#2b7fff33";
        readonly "fill-subtlest": "#09090b1a";
        readonly "fill-subtlest-hovered": "#09090b0d";
        readonly "fill-warning-subtlest": "#ff69001a";
        readonly "fill-caution-subtlest": "#fcc8001a";
        readonly "fill-information-subtlest": "#2b7fff1a";
        readonly "fill-success-subtlest": "#00c9511a";
        readonly "fill-danger-subtlest": "#fb2c361a";
        readonly "fill-danger-hovered": "#e7000b";
        readonly "fill-warning-hovered": "#f54a00";
        readonly "fill-caution-hovered": "#efb100";
        readonly "fill-information-hovered": "#155dfc";
        readonly "fill-success-hovered": "#00a63e";
        readonly "fill-debug": "#8e51ff";
        readonly "fill-debug-hovered": "#7f22fe";
        readonly "fill-debug-subtle": "#8e51ff4d";
        readonly "fill-debug-subtler": "#8e51ff33";
        readonly "fill-debug-subtlest": "#8e51ff1a";
        readonly "fill-control-surface-disabled": "#fafafa";
        readonly "fill-brand-subtler": "#155dfc4d";
        readonly "fill-rb": "#e6331b";
        readonly "fill-rb-hovered": "#cf2d18";
        readonly "fill-rb-subtle": "#e6331b80";
        readonly "fill-rb-subtler": "#e6331b4d";
        readonly "fill-rb-subtlest": "#e6331b1a";
        readonly "fill-icon-program": "#5c9cff";
        readonly "fill-brand-subtlest": "#155dfc1a";
        readonly "fill-navy": "#0b558c";
        readonly "fill-navy-hovered": "#094a7a";
        readonly "fill-navy-subtle": "#0b558c80";
        readonly "fill-navy-subtler": "#0b558c33";
        readonly "fill-navy-subtlest": "#0b558c26";
        readonly "bg-dim": "#09090b80";
        readonly "bg-default": "#fafafa";
        readonly "bg-overlay": "#f4f4f5";
        readonly "bg-inverse": "#09090b";
        readonly "bg-raised": "#f4f4f5";
        readonly "bg-card": "#ffffff";
        readonly "bg-alt-1": "#e4e4e7";
        readonly "bg-alt-2": "#d4d4d8";
        readonly "bg-translucent": "#fafafa80";
        readonly "bg-overlay-high": "#e4e4e7";
        readonly "bg-tooltip": "#18181b";
    };
    readonly dark: {
        readonly "fg-default": "#fafafa";
        readonly "fg-danger-subtle": "#fb2c364d";
        readonly "fg-danger": "#fb2c36";
        readonly "fg-warning-subtle": "#ff690080";
        readonly "fg-warning": "#ff6900";
        readonly "fg-success-subtle": "#00c95180";
        readonly "fg-success": "#00c951";
        readonly "fg-information-subtle": "#2b7fff80";
        readonly "fg-information": "#2b7fff";
        readonly "fg-disabled": "#fafafa33";
        readonly "fg-inverse": "#09090b";
        readonly "fg-subtlest": "#fafafa4d";
        readonly "fg-subtle": "#fafafa99";
        readonly "fg-subtler": "#fafafa66";
        readonly "fg-inverse-disabled": "#09090b26";
        readonly "fg-brand": "#155dfc";
        readonly "fg-brand-subtle": "#155dfc80";
        readonly "fg-default-hovered": "#fafafacc";
        readonly "fg-brand-hovered": "#154dd0";
        readonly "fg-caution": "#fcc800";
        readonly "fg-caution-subtle": "#fcc80080";
        readonly "fg-static-white": "#ffffff";
        readonly "fg-static-white-subtle": "#71717b";
        readonly "fg-debug": "#8e51ff";
        readonly "fg-debug-subtle": "#8e51ff80";
        readonly "fg-rb": "#e6331b";
        readonly "fg-rb-subtle": "#e6331b80";
        readonly "fg-navy": "#0b558c";
        readonly "fg-navy-subtle": "#0b558c80";
        readonly "fg-navy-hovered": "#094a7a";
        readonly "border-default": "#fafafa4d";
        readonly "border-danger-stronger": "#fb2c36";
        readonly "border-warning-stronger": "#ff6900";
        readonly "border-success-stronger": "#00c951";
        readonly "border-information-stronger": "#2b7fff";
        readonly "border-disabled": "#fafafa0d";
        readonly "border-inverse-stronger": "#09090be6";
        readonly "border-stronger": "#fafafae6";
        readonly "border-inverse": "#09090b33";
        readonly "border-danger": "#fb2c3680";
        readonly "border-warning": "#ff690080";
        readonly "border-information": "#2b7fff80";
        readonly "border-success": "#00c95180";
        readonly "border-subtle": "#fafafa26";
        readonly "border-input-focused": "#fafafae6";
        readonly "border-inverse-disabled": "#09090b1a";
        readonly "border-brand-stronger": "#155dfc";
        readonly "border-brand": "#155dfc80";
        readonly "border-caution-stronger": "#fcc800";
        readonly "border-caution": "#fcc80080";
        readonly "border-debug-stronger": "#8e51ff";
        readonly "border-debug": "#8e51ff80";
        readonly "border-subtler": "#fafafa1a";
        readonly "border-rb-stronger": "#e6331b";
        readonly "border-rb": "#e6331b80";
        readonly "border-navy-stronger": "#0b558c";
        readonly "border-navy": "#0b558c80";
        readonly "fill-danger-subtle": "#fb2c364d";
        readonly "fill-danger": "#fb2c36";
        readonly "fill-warning-subtle": "#ff69004d";
        readonly "fill-warning": "#ff6900";
        readonly "fill-success-subtle": "#00c9514d";
        readonly "fill-success": "#00c951";
        readonly "fill-information-subtle": "#2b7fff4d";
        readonly "fill-information": "#2b7fff";
        readonly "fill-disabled": "#fafafa0d";
        readonly "fill-control-surface": "#09090b80";
        readonly "fill-inverse": "#18181b";
        readonly "fill-inverse-hovered": "#3f3f46";
        readonly "fill-subtle": "#fafafa66";
        readonly "fill-subtle-hovered": "#fafafa4d";
        readonly "fill-transparent": "#ffffff00";
        readonly "fill-transparent-hovered": "#fafafa0d";
        readonly "fill-default": "#f4f4f5";
        readonly "fill-default-hovered": "#d4d4d8";
        readonly "fill-inverse-subtle": "#09090b66";
        readonly "fill-inverse-subtle-hovered": "#09090b4d";
        readonly "fill-inverse-disabled": "#09090b1a";
        readonly "fill-brand": "#155dfc";
        readonly "fill-brand-subtle": "#155dfc80";
        readonly "fill-subtler": "#fafafa33";
        readonly "fill-subtler-hovered": "#fafafa26";
        readonly "fill-brand-hovered": "#154dd0";
        readonly "fill-control-surface-hovered": "#09090b4d";
        readonly "fill-caution-subtle": "#fcc8004d";
        readonly "fill-caution": "#fcc800";
        readonly "fill-danger-subtler": "#fb2c3633";
        readonly "fill-warning-subtler": "#ff690033";
        readonly "fill-caution-subtler": "#fcc80033";
        readonly "fill-success-subtler": "#00c95133";
        readonly "fill-information-subtler": "#2b7fff33";
        readonly "fill-subtlest": "#fafafa1a";
        readonly "fill-subtlest-hovered": "#fafafa0d";
        readonly "fill-warning-subtlest": "#ff69001a";
        readonly "fill-caution-subtlest": "#fcc8001a";
        readonly "fill-information-subtlest": "#2b7fff1a";
        readonly "fill-success-subtlest": "#00c9511a";
        readonly "fill-danger-subtlest": "#fb2c361a";
        readonly "fill-danger-hovered": "#e7000b";
        readonly "fill-warning-hovered": "#f54a00";
        readonly "fill-caution-hovered": "#efb100";
        readonly "fill-information-hovered": "#155dfc";
        readonly "fill-success-hovered": "#00a63e";
        readonly "fill-debug": "#8e51ff";
        readonly "fill-debug-hovered": "#7f22fe";
        readonly "fill-debug-subtle": "#8e51ff4d";
        readonly "fill-debug-subtler": "#8e51ff33";
        readonly "fill-debug-subtlest": "#8e51ff1a";
        readonly "fill-control-surface-disabled": "#09090b40";
        readonly "fill-brand-subtler": "#155dfc4d";
        readonly "fill-rb": "#e6331b";
        readonly "fill-rb-hovered": "#cf2d18";
        readonly "fill-rb-subtle": "#e6331b80";
        readonly "fill-rb-subtler": "#e6331b4d";
        readonly "fill-rb-subtlest": "#e6331b1a";
        readonly "fill-icon-program": "#5c9cff";
        readonly "fill-brand-subtlest": "#155dfc1a";
        readonly "fill-navy": "#0b558c";
        readonly "fill-navy-hovered": "#094a7a";
        readonly "fill-navy-subtle": "#0b558c80";
        readonly "fill-navy-subtler": "#0b558c33";
        readonly "fill-navy-subtlest": "#0b558c26";
        readonly "bg-dim": "#09090bcc";
        readonly "bg-default": "#09090b";
        readonly "bg-overlay": "#3f3f46";
        readonly "bg-inverse": "#ffffff";
        readonly "bg-raised": "#2a2a2d";
        readonly "bg-card": "#fafafa1a";
        readonly "bg-alt-1": "#18181b";
        readonly "bg-alt-2": "#232326";
        readonly "bg-translucent": "#09090b99";
        readonly "bg-overlay-high": "#52525c";
        readonly "bg-tooltip": "#fafafa";
    };
};
export type RbColorKey = keyof typeof colors.light;
export declare const spacing: {
    readonly "0": 0;
    readonly "1": 4;
    readonly "2": 8;
    readonly "3": 12;
    readonly "4": 16;
    readonly "5": 20;
    readonly "6": 24;
    readonly "7": 28;
    readonly "8": 32;
    readonly "9": 36;
    readonly "10": 40;
    readonly "11": 44;
    readonly "12": 48;
    readonly "14": 56;
    readonly "16": 64;
    readonly "20": 80;
    readonly "24": 96;
    readonly "28": 112;
    readonly "32": 128;
    readonly "36": 144;
    readonly "40": 160;
    readonly "44": 176;
    readonly "48": 192;
    readonly "50": 200;
    readonly "3_5": 14;
    readonly "1_5": 6;
    readonly "0_5": 2;
    readonly "2_5": 10;
};
export declare const height: {
    readonly "1": 4;
    readonly "2": 8;
    readonly "3": 12;
    readonly "4": 16;
    readonly "5": 20;
    readonly "6": 24;
    readonly "7": 28;
    readonly "8": 32;
    readonly "9": 36;
    readonly "10": 40;
    readonly "12": 48;
    readonly "14": 56;
};
export declare const width: {
    readonly "1": 4;
    readonly "2": 8;
    readonly "3": 12;
    readonly "4": 16;
    readonly "5": 20;
    readonly "6": 24;
    readonly "7": 28;
    readonly "8": 32;
    readonly "9": 36;
    readonly "10": 40;
    readonly "12": 48;
    readonly "14": 56;
};
export declare const borderWidth: {
    readonly border: 1;
    readonly "border-2": 2;
    readonly "border-3": 3;
    readonly "border-4": 4;
};
export declare const rounded: {
    readonly full: 9999;
    readonly "4xl": 32;
    readonly "3xl": 24;
    readonly "2xl": 16;
    readonly xl: 12;
    readonly sm: 4;
    readonly lg: 8;
    readonly md: 6;
    readonly xs: 2;
};
export declare const font: {
    readonly family: {
        readonly sans: "Pretendard Variable";
        readonly superellipse: "Oxanium";
    };
    readonly size: {
        readonly xs: 12;
        readonly sm: 14;
        readonly base: 16;
        readonly lg: 18;
        readonly xl: 20;
        readonly "2xl": 24;
        readonly "3xl": 30;
        readonly "4xl": 36;
        readonly "5xl": 48;
        readonly "10px": 10;
        readonly "13px": 13;
        readonly "15px": 15;
    };
    readonly weight: {
        readonly thin: 100;
        readonly extralight: 200;
        readonly light: 300;
        readonly normal: 400;
        readonly medium: 500;
        readonly semibold: 600;
        readonly bold: 700;
        readonly extrabold: 800;
        readonly black: 900;
    };
    readonly tracking: {
        readonly tighter: -0.8;
        readonly tight: -0.4;
        readonly normal: 0;
        readonly wide: 0.4;
        readonly wider: 0.8;
        readonly widest: 1.6;
    };
    readonly leading: {
        readonly "3": 12;
        readonly "4": 16;
        readonly "5": 20;
        readonly "6": 24;
        readonly "7": 28;
        readonly "8": 32;
        readonly "9": 36;
        readonly "10": 40;
        readonly "11": 44;
        readonly "12": 48;
        readonly "13": 52;
        readonly "14": 56;
        readonly "15": 60;
        readonly "16": 64;
        readonly "3_5": 14;
        readonly "4_5": 18;
        readonly "5_5": 22;
        readonly "6_5": 26;
        readonly "7_5": 30;
        readonly "13_5": 54;
    };
};
export declare const typography: {
    readonly "title-01-normal": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 16;
        readonly lineHeight: 24;
        readonly fontWeight: "400";
        readonly letterSpacing: 0;
    };
    readonly "title-01-medium": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 16;
        readonly lineHeight: 24;
        readonly fontWeight: "500";
        readonly letterSpacing: 0;
    };
    readonly "title-01-bold": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 16;
        readonly lineHeight: 24;
        readonly fontWeight: "700";
        readonly letterSpacing: 0;
    };
    readonly "title-02-normal": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 18;
        readonly lineHeight: 28;
        readonly fontWeight: "400";
        readonly letterSpacing: 0;
    };
    readonly "title-02-medium": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 18;
        readonly lineHeight: 28;
        readonly fontWeight: "500";
        readonly letterSpacing: 0;
    };
    readonly "title-02-bold": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 18;
        readonly lineHeight: 28;
        readonly fontWeight: "700";
        readonly letterSpacing: 0;
    };
    readonly "title-03-normal": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 20;
        readonly lineHeight: 32;
        readonly fontWeight: "400";
        readonly letterSpacing: 0;
    };
    readonly "title-03-medium": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 20;
        readonly lineHeight: 32;
        readonly fontWeight: "500";
        readonly letterSpacing: 0;
    };
    readonly "title-03-bold": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 20;
        readonly lineHeight: 32;
        readonly fontWeight: "700";
        readonly letterSpacing: 0;
    };
    readonly "title-04-normal": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 24;
        readonly lineHeight: 36;
        readonly fontWeight: "400";
        readonly letterSpacing: 0;
    };
    readonly "title-04-medium": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 24;
        readonly lineHeight: 36;
        readonly fontWeight: "500";
        readonly letterSpacing: 0;
    };
    readonly "title-04-bold": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 24;
        readonly lineHeight: 36;
        readonly fontWeight: "700";
        readonly letterSpacing: 0;
    };
    readonly "title-05-normal": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 30;
        readonly lineHeight: 44;
        readonly fontWeight: "400";
        readonly letterSpacing: 0;
    };
    readonly "title-05-medium": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 30;
        readonly lineHeight: 44;
        readonly fontWeight: "500";
        readonly letterSpacing: 0;
    };
    readonly "title-05-bold": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 30;
        readonly lineHeight: 44;
        readonly fontWeight: "700";
        readonly letterSpacing: 0;
    };
    readonly "title-06-normal": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 36;
        readonly lineHeight: 54;
        readonly fontWeight: "400";
        readonly letterSpacing: 0;
    };
    readonly "title-06-medium": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 36;
        readonly lineHeight: 54;
        readonly fontWeight: "500";
        readonly letterSpacing: 0;
    };
    readonly "title-06-bold": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 36;
        readonly lineHeight: 54;
        readonly fontWeight: "700";
        readonly letterSpacing: 0;
    };
    readonly "body-lg-normal": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 18;
        readonly lineHeight: 32;
        readonly fontWeight: "400";
        readonly letterSpacing: 0;
    };
    readonly "body-lg-medium": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 18;
        readonly lineHeight: 32;
        readonly fontWeight: "500";
        readonly letterSpacing: 0;
    };
    readonly "body-lg-semibold": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 18;
        readonly lineHeight: 32;
        readonly fontWeight: "600";
        readonly letterSpacing: 0;
    };
    readonly "body-md-normal": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 16;
        readonly lineHeight: 28;
        readonly fontWeight: "400";
        readonly letterSpacing: 0;
    };
    readonly "body-md-medium": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 16;
        readonly lineHeight: 28;
        readonly fontWeight: "500";
        readonly letterSpacing: 0;
    };
    readonly "body-md-semibold": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 16;
        readonly lineHeight: 28;
        readonly fontWeight: "600";
        readonly letterSpacing: 0;
    };
    readonly "body-sm2-normal": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 15;
        readonly lineHeight: 26;
        readonly fontWeight: "400";
        readonly letterSpacing: 0;
    };
    readonly "body-sm2-medium": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 15;
        readonly lineHeight: 26;
        readonly fontWeight: "500";
        readonly letterSpacing: 0;
    };
    readonly "body-sm2-semibold": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 15;
        readonly lineHeight: 26;
        readonly fontWeight: "600";
        readonly letterSpacing: 0;
    };
    readonly "body-sm-normal": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 14;
        readonly lineHeight: 24;
        readonly fontWeight: "400";
        readonly letterSpacing: 0;
    };
    readonly "body-sm-medium": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 14;
        readonly lineHeight: 24;
        readonly fontWeight: "500";
        readonly letterSpacing: 0;
    };
    readonly "body-sm-semibold": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 14;
        readonly lineHeight: 24;
        readonly fontWeight: "600";
        readonly letterSpacing: 0;
    };
    readonly "body-xs2-normal": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 13;
        readonly lineHeight: 22;
        readonly fontWeight: "400";
        readonly letterSpacing: 0;
    };
    readonly "body-xs2-medium": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 13;
        readonly lineHeight: 22;
        readonly fontWeight: "500";
        readonly letterSpacing: 0;
    };
    readonly "body-xs2-semibold": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 13;
        readonly lineHeight: 22;
        readonly fontWeight: "600";
        readonly letterSpacing: 0;
    };
    readonly "body-xs-normal": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 12;
        readonly lineHeight: 20;
        readonly fontWeight: "400";
        readonly letterSpacing: 0;
    };
    readonly "body-xs-medium": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 12;
        readonly lineHeight: 20;
        readonly fontWeight: "500";
        readonly letterSpacing: 0;
    };
    readonly "body-xs-semibold": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 12;
        readonly lineHeight: 20;
        readonly fontWeight: "600";
        readonly letterSpacing: 0;
    };
    readonly "body-2xs-normal": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 10;
        readonly lineHeight: 16;
        readonly fontWeight: "400";
        readonly letterSpacing: 0;
    };
    readonly "body-2xs-medium": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 10;
        readonly lineHeight: 16;
        readonly fontWeight: "500";
        readonly letterSpacing: 0;
    };
    readonly "body-2xs-semibold": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 10;
        readonly lineHeight: 16;
        readonly fontWeight: "600";
        readonly letterSpacing: 0;
    };
    readonly "compact-lg-normal": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 18;
        readonly lineHeight: 28;
        readonly fontWeight: "400";
        readonly letterSpacing: 0;
    };
    readonly "compact-lg-medium": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 18;
        readonly lineHeight: 28;
        readonly fontWeight: "500";
        readonly letterSpacing: 0;
    };
    readonly "compact-lg-semibold": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 18;
        readonly lineHeight: 28;
        readonly fontWeight: "600";
        readonly letterSpacing: 0;
    };
    readonly "compact-md-normal": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 16;
        readonly lineHeight: 24;
        readonly fontWeight: "400";
        readonly letterSpacing: 0;
    };
    readonly "compact-md-medium": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 16;
        readonly lineHeight: 24;
        readonly fontWeight: "500";
        readonly letterSpacing: 0;
    };
    readonly "compact-md-semibold": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 16;
        readonly lineHeight: 24;
        readonly fontWeight: "600";
        readonly letterSpacing: 0;
    };
    readonly "compact-sm2-normal": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 15;
        readonly lineHeight: 22;
        readonly fontWeight: "400";
        readonly letterSpacing: 0;
    };
    readonly "compact-sm2-medium": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 15;
        readonly lineHeight: 22;
        readonly fontWeight: "500";
        readonly letterSpacing: 0;
    };
    readonly "compact-sm2-semibold": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 15;
        readonly lineHeight: 22;
        readonly fontWeight: "600";
        readonly letterSpacing: 0;
    };
    readonly "compact-sm-normal": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 14;
        readonly lineHeight: 20;
        readonly fontWeight: "400";
        readonly letterSpacing: 0;
    };
    readonly "compact-sm-medium": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 14;
        readonly lineHeight: 20;
        readonly fontWeight: "500";
        readonly letterSpacing: 0;
    };
    readonly "compact-sm-semibold": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 14;
        readonly lineHeight: 20;
        readonly fontWeight: "600";
        readonly letterSpacing: 0;
    };
    readonly "compact-xs2-normal": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 13;
        readonly lineHeight: 18;
        readonly fontWeight: "400";
        readonly letterSpacing: 0;
    };
    readonly "compact-xs2-medium": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 13;
        readonly lineHeight: 18;
        readonly fontWeight: "500";
        readonly letterSpacing: 0;
    };
    readonly "compact-xs2-semibold": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 13;
        readonly lineHeight: 18;
        readonly fontWeight: "600";
        readonly letterSpacing: 0;
    };
    readonly "compact-xs-normal": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 12;
        readonly lineHeight: 16;
        readonly fontWeight: "400";
        readonly letterSpacing: 0;
    };
    readonly "compact-xs-medium": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 12;
        readonly lineHeight: 16;
        readonly fontWeight: "500";
        readonly letterSpacing: 0;
    };
    readonly "compact-xs-semibold": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 12;
        readonly lineHeight: 16;
        readonly fontWeight: "600";
        readonly letterSpacing: 0;
    };
    readonly "compact-2xs-normal": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 10;
        readonly lineHeight: 12;
        readonly fontWeight: "400";
        readonly letterSpacing: 0;
    };
    readonly "compact-2xs-medium": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 10;
        readonly lineHeight: 12;
        readonly fontWeight: "500";
        readonly letterSpacing: 0;
    };
    readonly "compact-2xs-semibold": {
        readonly fontFamily: "Pretendard Variable";
        readonly fontSize: 10;
        readonly lineHeight: 12;
        readonly fontWeight: "600";
        readonly letterSpacing: 0;
    };
    readonly "code-2xs-normal": {
        readonly fontFamily: "Oxanium";
        readonly fontSize: 10;
        readonly lineHeight: 12;
        readonly fontWeight: "400";
        readonly letterSpacing: 0;
    };
    readonly "code-2xs-medium": {
        readonly fontFamily: "Oxanium";
        readonly fontSize: 10;
        readonly lineHeight: 12;
        readonly fontWeight: "500";
        readonly letterSpacing: 0;
    };
    readonly "code-2xs-semibold": {
        readonly fontFamily: "Oxanium";
        readonly fontSize: 10;
        readonly lineHeight: 12;
        readonly fontWeight: "600";
        readonly letterSpacing: 0;
    };
    readonly "code-xs-normal": {
        readonly fontFamily: "Oxanium";
        readonly fontSize: 12;
        readonly lineHeight: 14;
        readonly fontWeight: "400";
        readonly letterSpacing: 0;
    };
    readonly "code-xs-medium": {
        readonly fontFamily: "Oxanium";
        readonly fontSize: 12;
        readonly lineHeight: 14;
        readonly fontWeight: "500";
        readonly letterSpacing: 0;
    };
    readonly "code-xs-semibold": {
        readonly fontFamily: "Oxanium";
        readonly fontSize: 12;
        readonly lineHeight: 14;
        readonly fontWeight: "600";
        readonly letterSpacing: 0;
    };
    readonly "code-xs2-semibold": {
        readonly fontFamily: "Oxanium";
        readonly fontSize: 13;
        readonly lineHeight: 18;
        readonly fontWeight: "600";
        readonly letterSpacing: 0;
    };
    readonly "code-xs2-medium": {
        readonly fontFamily: "Oxanium";
        readonly fontSize: 13;
        readonly lineHeight: 18;
        readonly fontWeight: "500";
        readonly letterSpacing: 0;
    };
    readonly "code-xs2-normal": {
        readonly fontFamily: "Oxanium";
        readonly fontSize: 13;
        readonly lineHeight: 18;
        readonly fontWeight: "400";
        readonly letterSpacing: 0;
    };
    readonly "code-sm-semibold": {
        readonly fontFamily: "Oxanium";
        readonly fontSize: 14;
        readonly lineHeight: 20;
        readonly fontWeight: "600";
        readonly letterSpacing: 0;
    };
    readonly "code-sm-medium": {
        readonly fontFamily: "Oxanium";
        readonly fontSize: 14;
        readonly lineHeight: 20;
        readonly fontWeight: "500";
        readonly letterSpacing: 0;
    };
    readonly "code-sm-normal": {
        readonly fontFamily: "Oxanium";
        readonly fontSize: 14;
        readonly lineHeight: 20;
        readonly fontWeight: "400";
        readonly letterSpacing: 0;
    };
    readonly "code-sm2-semibold": {
        readonly fontFamily: "Oxanium";
        readonly fontSize: 15;
        readonly lineHeight: 22;
        readonly fontWeight: "600";
        readonly letterSpacing: 0;
    };
    readonly "code-sm2-medium": {
        readonly fontFamily: "Oxanium";
        readonly fontSize: 15;
        readonly lineHeight: 22;
        readonly fontWeight: "500";
        readonly letterSpacing: 0;
    };
    readonly "code-sm2-normal": {
        readonly fontFamily: "Oxanium";
        readonly fontSize: 15;
        readonly lineHeight: 22;
        readonly fontWeight: "400";
        readonly letterSpacing: 0;
    };
    readonly "code-md-semibold": {
        readonly fontFamily: "Oxanium";
        readonly fontSize: 16;
        readonly lineHeight: 24;
        readonly fontWeight: "600";
        readonly letterSpacing: 0;
    };
    readonly "code-md-medium": {
        readonly fontFamily: "Oxanium";
        readonly fontSize: 16;
        readonly lineHeight: 24;
        readonly fontWeight: "500";
        readonly letterSpacing: 0;
    };
    readonly "code-md-normal": {
        readonly fontFamily: "Oxanium";
        readonly fontSize: 16;
        readonly lineHeight: 24;
        readonly fontWeight: "400";
        readonly letterSpacing: 0;
    };
    readonly "code-lg-semibold": {
        readonly fontFamily: "Oxanium";
        readonly fontSize: 18;
        readonly lineHeight: 28;
        readonly fontWeight: "600";
        readonly letterSpacing: 0;
    };
    readonly "code-lg-medium": {
        readonly fontFamily: "Oxanium";
        readonly fontSize: 18;
        readonly lineHeight: 28;
        readonly fontWeight: "500";
        readonly letterSpacing: 0;
    };
    readonly "code-lg-normal": {
        readonly fontFamily: "Oxanium";
        readonly fontSize: 18;
        readonly lineHeight: 28;
        readonly fontWeight: "400";
        readonly letterSpacing: 0;
    };
};
export type RbTypoKey = keyof typeof typography;
export declare const shadow: {
    readonly "down-2xs": readonly [{
        readonly color: "#09090b33";
        readonly x: 0;
        readonly y: 0;
        readonly blur: 1;
        readonly spread: 0;
    }, {
        readonly color: "#09090b30";
        readonly x: 0;
        readonly y: 1;
        readonly blur: 4;
        readonly spread: 0;
    }];
    readonly "down-xs": readonly [{
        readonly color: "#09090b33";
        readonly x: 0;
        readonly y: 0;
        readonly blur: 1;
        readonly spread: 0;
    }, {
        readonly color: "#09090b2e";
        readonly x: 0;
        readonly y: 4;
        readonly blur: 10;
        readonly spread: 0;
    }];
    readonly "down-sm": readonly [{
        readonly color: "#09090b33";
        readonly x: 0;
        readonly y: 0;
        readonly blur: 1;
        readonly spread: 0;
    }, {
        readonly color: "#09090b2b";
        readonly x: 0;
        readonly y: 10;
        readonly blur: 16;
        readonly spread: 0;
    }];
    readonly "down-md": readonly [{
        readonly color: "#09090b33";
        readonly x: 0;
        readonly y: 0;
        readonly blur: 2;
        readonly spread: 0;
    }, {
        readonly color: "#09090b29";
        readonly x: 0;
        readonly y: 20;
        readonly blur: 32;
        readonly spread: 0;
    }];
    readonly "down-lg": readonly [{
        readonly color: "#09090b33";
        readonly x: 0;
        readonly y: 0;
        readonly blur: 1;
        readonly spread: 0;
    }, {
        readonly color: "#09090b26";
        readonly x: 0;
        readonly y: 34;
        readonly blur: 48;
        readonly spread: 0;
    }];
    readonly "down-xl": readonly [{
        readonly color: "#09090b33";
        readonly x: 0;
        readonly y: 0;
        readonly blur: 1;
        readonly spread: 0;
    }, {
        readonly color: "#09090b24";
        readonly x: 0;
        readonly y: 52;
        readonly blur: 64;
        readonly spread: 0;
    }];
    readonly "up-2xs": readonly [{
        readonly color: "#09090b33";
        readonly x: 0;
        readonly y: 0;
        readonly blur: 1;
        readonly spread: 0;
    }, {
        readonly color: "#09090b30";
        readonly x: 0;
        readonly y: -1;
        readonly blur: 4;
        readonly spread: 0;
    }];
    readonly "up-xs": readonly [{
        readonly color: "#09090b33";
        readonly x: 0;
        readonly y: 0;
        readonly blur: 1;
        readonly spread: 0;
    }, {
        readonly color: "#09090b2e";
        readonly x: 0;
        readonly y: -4;
        readonly blur: 10;
        readonly spread: 0;
    }];
    readonly "up-sm": readonly [{
        readonly color: "#09090b33";
        readonly x: 0;
        readonly y: 0;
        readonly blur: 1;
        readonly spread: 0;
    }, {
        readonly color: "#09090b2b";
        readonly x: 0;
        readonly y: -10;
        readonly blur: 16;
        readonly spread: 0;
    }];
    readonly "up-md": readonly [{
        readonly color: "#09090b33";
        readonly x: 0;
        readonly y: 0;
        readonly blur: 2;
        readonly spread: 0;
    }, {
        readonly color: "#09090b29";
        readonly x: 0;
        readonly y: -20;
        readonly blur: 32;
        readonly spread: 0;
    }];
    readonly "up-lg": readonly [{
        readonly color: "#09090b33";
        readonly x: 0;
        readonly y: 0;
        readonly blur: 1;
        readonly spread: 0;
    }, {
        readonly color: "#09090b26";
        readonly x: 0;
        readonly y: -34;
        readonly blur: 48;
        readonly spread: 0;
    }];
    readonly "up-xl": readonly [{
        readonly color: "#09090b33";
        readonly x: 0;
        readonly y: 0;
        readonly blur: 1;
        readonly spread: 0;
    }, {
        readonly color: "#09090b24";
        readonly x: 0;
        readonly y: -52;
        readonly blur: 64;
        readonly spread: 0;
    }];
};
export type RbShadowKey = keyof typeof shadow;
