"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.2
  Module: rbq_api.msg.dds_
  IDL file: Request_.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

@dataclass
@annotate.final
@annotate.autoid("sequential")
class Request_(idl.IdlStruct, typename="rbq_api.msg.dds_.Request_"):
    header: 'rbq_sdk_py.idl.rbq_api.msg.dds_.RequestHeader_'
    parameter: str
    binary: types.sequence[types.uint8]

