"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: std_msgs.msg.dds_
  IDL file: Float64MultiArray_.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types


@dataclass
@annotate.final
@annotate.autoid("sequential")
class Float64MultiArray_(idl.IdlStruct, typename="std_msgs.msg.dds_.Float64MultiArray_"):
    layout: 'rbq_sdk_py.idl.std_msgs.msg.dds_.MultiArrayLayout_'
    data: types.sequence[types.float64]
