"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: std_msgs.msg.dds_
  IDL file: MultiArrayDimension_.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types


@dataclass
@annotate.final
@annotate.autoid("sequential")
class MultiArrayDimension_(idl.IdlStruct, typename="std_msgs.msg.dds_.MultiArrayDimension_"):
    label: str
    size: types.uint32
    stride: types.uint32
