#include "Header_.idl"
#include "RegionOfInterest_.idl"

module sensor_msgs {
  module msg {
    module dds_ {
      @extensibility(FINAL)
      struct CameraInfo_ {
        std_msgs::msg::dds_::Header_ header;
        uint32 height;
        uint32 width;
        string distortion_model;
        sequence<double> d;
        double k[9];
        double r[9];
        double p[12];
        uint32 binning_x;
        uint32 binning_y;
        sensor_msgs::msg::dds_::RegionOfInterest_ roi;
      };
    };
  };
};
