// rcl_interfaces/msg/SetParametersResult
module rcl_interfaces {
  module msg {
    module dds_ {
      @extensibility(FINAL)
      struct SetParametersResult_ {
        boolean successful;
        string reason;
      };
    };
  };
};
