"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.2
  Module: rbq_msgs.msg.dds_
  IDL file: SystemLog_.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types


@dataclass
@annotate.final
@annotate.autoid("sequential")
class SystemLog_(idl.IdlStruct, typename="rbq_msgs.msg.dds_.SystemLog_"):
    header: 'rbq_sdk_py.idl.std_msgs.msg.dds_.Header_'
    log_level: str
    log_msg: str
