"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: nav_msgs.msg.dds_
  IDL file: Odometry_.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types


@dataclass
@annotate.final
@annotate.autoid("sequential")
class Odometry_(idl.IdlStruct, typename="nav_msgs.msg.dds_.Odometry_"):
    header: 'rbq_sdk_py.idl.std_msgs.msg.dds_.Header_'
    child_frame_id: str
    pose: 'rbq_sdk_py.idl.geometry_msgs.msg.dds_.PoseWithCovariance_'
    twist: 'rbq_sdk_py.idl.geometry_msgs.msg.dds_.TwistWithCovariance_'
