name: Release & Update Latest Tag

on:
  push:
    paths:
      - 'hex/*.hex'

jobs:
  release-and-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Find updated hex file
        id: hexinfo
        run: |
          FILE=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^hex/.*\.hex$' | head -n 1)
          echo "Found file: $FILE"

          if [[ "$FILE" == hex/QuadLeg_b91_f* ]]; then
            TYPE=QuadLeg
          elif [[ "$FILE" == hex/PDU_b40_f* ]]; then
            TYPE=PDU
          else
            echo "Unrecognized hex file format"
            exit 1
          fi

          F_VER=$(echo "$FILE" | grep -oP 'f\K[0-9]+')
          MAJOR=0
          MINOR=$((F_VER / 10))
          PATCH=$((F_VER % 10))
          VERSION=v${MAJOR}.${MINOR}.${PATCH}

          echo "type=$TYPE" >> $GITHUB_OUTPUT
          echo "version_tag=${TYPE}-${VERSION}" >> $GITHUB_OUTPUT
          echo "latest_tag=${TYPE}-latest" >> $GITHUB_OUTPUT
          echo "filename=$(basename $FILE)" >> $GITHUB_OUTPUT
          echo "filepath=$FILE" >> $GITHUB_OUTPUT

      - name: Create version tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ steps.hexinfo.outputs.version_tag }} $GITHUB_SHA
          git push origin ${{ steps.hexinfo.outputs.version_tag }}

      - name: Update latest tag (force)
        run: |
          git tag -f ${{ steps.hexinfo.outputs.latest_tag }} $GITHUB_SHA
          git push -f origin ${{ steps.hexinfo.outputs.latest_tag }}

      - name: Create tar.gz for latest
        run: |
          mkdir -p tmp_release
          cp ${{ steps.hexinfo.outputs.filepath }} tmp_release/
          tar -czf ${{ steps.hexinfo.outputs.type }}.tar.gz -C tmp_release $(basename ${{ steps.hexinfo.outputs.filepath }})

      - name: Upload versioned release (.hex)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.hexinfo.outputs.version_tag }}
          files: ${{ steps.hexinfo.outputs.filepath }}

      - name: Upload latest release (.tar.gz)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.hexinfo.outputs.latest_tag }}
          files: ${{ steps.hexinfo.outputs.type }}.tar.gz

