# Mirrors unitree::robot::a2::ROBOT_SPORT_* / unitree_sdk2py.a2.sport.sport_api

# service identity
SPORT_SERVICE_NAME = "sport"
SPORT_API_VERSION  = "1.0.0.1"

# api ids
SPORT_API_ID_DAMP            = 1001
SPORT_API_ID_BALANCESTAND    = 1002
SPORT_API_ID_STOPMOVE        = 1003
SPORT_API_ID_STANDUP         = 1004
SPORT_API_ID_STANDDOWN       = 1005
SPORT_API_ID_RECOVERYSTAND   = 1006
SPORT_API_ID_EULER           = 1007
SPORT_API_ID_MOVE            = 1008
SPORT_API_ID_BODYPOSITION    = 1009
SPORT_API_ID_SWITCHGAIT      = 1011
SPORT_API_ID_BODYHEIGHT      = 1013
SPORT_API_ID_SPEEDLEVEL      = 1015
SPORT_API_ID_LEFTSIDEGAIT    = 1016
SPORT_API_ID_RIGHTSIDEGAIT   = 1017
SPORT_API_ID_HANDSTAND       = 1018
SPORT_API_ID_BIPEDSTAND      = 1019
SPORT_API_ID_FRONTFLIP       = 1020
SPORT_API_ID_BACKFLIP        = 1021
SPORT_API_ID_GETSTATE        = 1034
SPORT_API_ID_SETAUTORECOVERY = 1040

# gait/mode ids — argument values for SwitchGait
ID_DEFAULT_MODE     = 0
ID_RUNNING_MODE     = 1
ID_CLIMB_MODE       = 2

# error codes
SPORT_ERR_SERVER_OVERTIME  = 4201
SPORT_ERR_SERVER_NOT_INIT  = 4205
